"""market stats

Revision ID: c2308e947720
Revises: 09cd517896b0
Create Date: 2026-08-20 16:46:47.338507
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c2308e947720'
down_revision: str | None = '09cd517896b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_stats',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('lots', sa.Integer(), nullable=False),
    sa.Column('sample', sa.Integer(), nullable=False),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_avg', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('pmax', sa.Integer(), nullable=True),
    sa.Column('spam', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_stats')
    # ### end Alembic commands ###
